name: Node.js CI

on:
        push:
                branches: [deploy]

jobs:
        build:
                runs-on: ubuntu-latest
                strategy:
                        matrix:
                                node-version: [14.x]

                steps:
                        - uses: actions/checkout@v2
                        - name: Use Node.js ${{ matrix.node-version }}
                          uses: actions/setup-node@v1
                          with:
                                  node-version: ${{ matrix.node-version }}

                        - name: Installing my packages
                          run: cd client && npm install

                        - run: cd client && npm run export
                          env:
                                  NEXT_PUBLIC_BASE_PATH: /portfolio

                        - name: Deploy 🚀
                          uses: JamesIves/github-pages-deploy-action@3.5.9
                          with:
                                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                                  BRANCH: main
                                  FOLDER: client/out
